package question.question300_399;

/*
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output:
 * e
 * Explanation:
 * 'e' is the letter that was added.
 */
import java.util.Arrays;

//对两个String对应的char[]进行排序再比较——果然是麻烦啊！！！
public class Question389_own1 {
	public char findTheDifference(String s, String t) {
		char[] sl = s.toCharArray();
		char[] tl = t.toCharArray();
		Arrays.sort(sl);
		Arrays.sort(tl);
		for (int i = 0; i < s.length(); i++)
			if (sl[i] != tl[i])
				return tl[i];
		return tl[tl.length - 1];
	}
}
